apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: emqx-access
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
  - nonResourceURLs: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: emqx-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: emqx-access
subjects:
  - kind: ServiceAccount
    name: emqx
    namespace: default
